version: '3.9'
services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: concesionaria
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  # Aquí puedes agregar otros servicios, como tu aplicación Spring Boot, si la deseas ejecutar en Docker.

volumes:
  postgres_data:
    driver: local

